// GPIO
#define GPIO_BRAIN_MIDI_RX 9

#define GPIO_BRAIN_LED_1 10
#define GPIO_BRAIN_LED_2 11
#define GPIO_BRAIN_LED_3 12
#define GPIO_BRAIN_LED_4 13
#define GPIO_BRAIN_LED_5 14
#define GPIO_BRAIN_LED_6 15

#define GPIO_BRAIN_BUTTON_1 18
#define GPIO_BRAIN_BUTTON_2 19

#define GPIO_BRAIN_PULSE_INPUT 4
#define GPIO_BRAIN_PULSE_OUTPUT 8

#define GPIO_BRAIN_POTMUX_ADC 26
#define GPIO_BRAIN_POTMUX_S0 16
#define GPIO_BRAIN_POTMUX_S1 17

#define GPIO_BRAIN_AUDIO_CV_OUT_SCK 2
#define GPIO_BRAIN_AUDIO_CV_OUT_TX 3
#define GPIO_BRAIN_AUDIO_CV_OUT_CS 5
#define GPIO_BRAIN_AUDIO_CV_OUT_COUPLING_A 6
#define GPIO_BRAIN_AUDIO_CV_OUT_COUPLING_B 7

#define GPIO_BRAIN_AUDIO_CV_IN_A 27
#define GPIO_BRAIN_AUDIO_CV_IN_B 28
